- charts/bookkeeper/Chart.yaml
- charts/bookkeeper/README.md
- charts/bookkeeper/values.yaml
Updating bookkeeper charts to use bookkeeper image 0.9.1
Fixes #14 
Updates the AppVersion and the image version to 0.9.1 inside the bookkeeper charts.
Running the following commands should install the bookkeeper cluster with image 0.9.1
```
helm repo add pravega https://charts.pravega.io
helm repo update
helm install bookkeeper pravega/bookkeeper
```
> [bookkeeper] Issue 14: Updating bookkeeper image version to 0.9.1

- charts/bookkeeper-operator/Chart.yaml
Bumps up the bookkeeper operator chart version to 0.2.1
Fixes #16 
Bumps up the bookkeeper operator chart version to 0.2.1
Not applicable
> [bookkeeper-operator] Issue 16: Bumping bookeeper operator chart version

- charts/pravega-operator/Chart.yaml
- charts/pravega-operator/README.md
- charts/pravega-operator/values.yaml
Deprecates the supported versions configmap from the pravega operator charts. The version map will be completely removed in a later operator release.
Fixes #20 
This change along with [this](https://github.com/pravega/pravega-operator/pull/565) PR on the pravega operator repository helps us get rid of the version map dependency.
The pravega operator installed using the latest charts should allow installation of any pravega version given in the correct format (i.e. *MAJOR*.*MINOR*.*PATCH*-*XXXX*), and should also allow upgrades to any other pravega version. Downgrades are however not allowed.
> [pravega-operator] Issue 20: Deprecating supported versions map

- charts/bookkeeper/templates/bookkeeper.yaml
- charts/bookkeeper/values.yaml
How the ~~pravega &~~ bk (cluster) charts specify their image is different than how the bk-operator, pravega-operator, zk-operator, and zk-cluster specify their image. Specifically, the former do:
```
version: x.y.z
```
and the rest do:
```
image:
tag: x.y.z
```
To unify the format that the values are given to reduce bugs caused by improper usage due to the inconsistency.
Changes the format.
> [bookkeeper] Issue 18: make version format consistent

- charts/pravega/templates/pravega.yaml
- charts/pravega/values.yaml
How the pravega ~~& bk (cluster)~~ charts specify their image is different than how the bk-operator, pravega-operator, zk-operator, and zk-cluster specify their image. Specifically, the former do:
```
version: x.y.z
```
and the rest do:
```
image:
tag: x.y.z
```
To unify the format that the values are given to reduce bugs caused by improper usage due to the inconsistency.
Changes the format.
> [pravega] Issue 18: make version format consistent

- charts/pravega-operator/Chart.yaml
Bumps up the pravega operator chart version to 0.6.1
Fixes #24 
Bumps up the pravega operator chart version to 0.6.1
Not applicable
> [pravega-operator] Issue 24: Bumping pravega operator chart version

- charts/pravega/Chart.yaml
- charts/pravega/README.md
- charts/pravega/values.yaml
Updating pravega charts to use pravega image 0.9.1
Fixes #30 
Updates the AppVersion and the image version to 0.9.1 inside the pravega charts and the chart version to 0.10.0
Running the following commands should install the pravega cluster with image 0.9.1
```
helm repo add pravega https://charts.pravega.io
helm repo update
helm install pravega pravega/pravega 
```
> [pravega] Issue 30: Updating pravega chart version to 0.10.0 and image version to 0.9.1

- charts/bookkeeper/Chart.yaml
- charts/bookkeeper/README.md
Decouples the chart version of the bookkeeper charts from the underlying app version.
Fixes #6 
Decouples the chart version of the bookkeeper charts from the underlying app version.
The bookkeeper 0.10.0 charts should install the bookkeeper cluster version 0.9.1
> [bookkeeper] Issue 6: Separating chart version from app version

- charts/pravega/Chart.yaml
Bumps up the pravega chart version to 0.10.1
Fixes #33 
Bumps up the pravega chart version to 0.10.1
Not applicable
> [pravega] Issue 33: Bumping pravega chart version

- charts/pravega/README.md
- charts/pravega/templates/pravega.yaml
- charts/pravega/values.yaml
Adding support to configure influx db secret in pravega CR
Fixes #28
Added new fields in values files
Verified installation of Pravega charts
> [pravega] Issue 28: Add support to configure influxdb secret in pravega charts

- charts/pravega-operator/Chart.yaml
- charts/pravega-operator/README.md
- charts/pravega-operator/values.yaml
Updating pravega operator charts AppVersion to 0.5.5
Fixes #40 
Updating pravega operator charts AppVersion to 0.5.5
Should install pravega-operator 0.5.5
> [pravega-operator] Issue 40: Updating pravega operator charts AppVersion to 0.5.5

- charts/pravega-operator/Chart.yaml
Bumps up the pravega operator chart version to 0.6.2
Fixes #42 
Bumps up the pravega operator chart version to 0.6.2
N.A.
> [pravega-operator] Issue 42: Bumping pravega operator chart version

- charts/bookkeeper/templates/bookkeeper.yaml
Adding checks to take the default values for the volume claim template
Fixes #46
updates the bookkeeper template to take the default values for volume claim templates 
When deploying bookkeeper using charts , only provide values to certain fields of the `bookkeeper/values.yaml` storage object. In all the scenarios, if any of the value is not set by the user then it should be set to default.
Here are few scenarios to try out:
- Removing/ Commenting out the entire storage object
- Setting only className in ledger , journal and index 
- Setting only volumeSize in ledger , journal and index
- Setting only volumeSize in certain object (say ledger) and className in other (say index) and leaving both the fields of index unset
> [bookkeeper] Issue 46: Update bookkeeper template to take the default values for Volume Claim templates

- charts/bookkeeper-operator/Chart.yaml
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>
Bumps up the bookkeeper operator chart version to 0.2.2
Fixes #55 
Bumps up the bookkeeper operator chart version to 0.2.1
N.A.
> [bookkeeper-operator] Issue 55: Bumping chart version to 0.2.2

- charts/bookkeeper/Chart.yaml
Signed-off-by: SrishT <Srishti.Thakkar@emc.comT>
Bumps up the bookkeeper chart version to 0.10.2
Fixes #57 
Bumps up the bookkeeper chart version to 0.10.2
N.A.
> [bookkeeper] Issue 57: Bumping chart version to 0.10.2

- charts/pravega/README.md
- charts/pravega/templates/clusterrole.yaml
- charts/pravega/templates/clusterrolebinding.yaml
- charts/pravega/templates/pravega.yaml
- charts/pravega/templates/role.yaml
- charts/pravega/templates/rolebinding.yaml
- charts/pravega/templates/service_account.yaml
- charts/pravega/values.yaml
Currently, in the charts we are creating service account roles and role bindings if external access is enabled. But there is no check to enforce they are already present. Due to that after one cluster deployed, second cluster deployment failing with error resource already exists
Fixes #50
In charts, added a check to verify the existence of resources before  creating it
Verified that able to deploy more than one cluster with external access
> [pravega] Issue 50: Allow deployment of multiple pravega clusters with external access

- charts/pravega/templates/post-install-upgrade-rollback-hooks.yaml
Adding helm's `post-rollback` hooks so as to ensure that the rollback success or failure message is returned only when the rollback has completed successfully or failed , not immediately.
Fixes #62 
The code adds helm's post-rollback hooks in pravega charts in order for the the rollback success or failed message to be in sync with rollback failure or success
- Install a specific chart version of pravega (say 0.9.0)
- Upgrade the pravega to an not existing image (say 0.9.6) to purposefully fail the upgrade
- Now Rollback to the prevision version
The rollback success message `Rollback was a success! Happy Helming! `should appear once the rollback has completed successfully.
In case the rollback fails ,the following message should appear …
> [pravega] Issue 62: Adding Rollback hooks for Pravega

- charts/bookkeeper/templates/post-install-upgrade-rollback-hooks.yaml
Adding helm's `post-rollback` hooks so as to ensure that the rollback success or failure message is returned only when the rollback has completed successfully or failed , not immediately.
Fixes #59 
The code adds helm's post-rollback hooks in order for the the rollback success or failed message to be in sync with rollback failure or success
- Install a specific chart version of bookkeeper (say 0.9.0)
- Upgrade the bookkeeper to an not existing image (say 0.9.6) to purposefully fail the upgrade
- Now Rollback to the previous version
The rollback success message `Rollback was a success! Happy Helming!` should appear once the rollback has completed successfully.
In case the rollback fails ,the following message should appear `Error: …
> [bookkeeper] Issue 59: Adding rollback hooks for Bookkeeper

- charts/pravega/values.yaml
- charts/pravega/values/large.yaml
- charts/pravega/values/medium.yaml
- charts/pravega/values/small.yaml
Modifying the default values for JVM options **-Xmx** (maximum heap size of JVM) and **-XX:MaxDirectMemorySize** (segement store direct memory) and also the value of standard option, **pravegaservice.cache.size.max** (Segment Store read cache size)
Fixes #48 
While configuring the memory settings for segment store certain guidelines need to be followed as show below and the code fixes the same in all the sizing manifests
- Host Memory (Pod, VM) = JVM Heap (-Xmx) + JVM Direct Memory (-XX:MaxDirectMemorySize) + unallocated Memory 
where unallocated memory should be in range of (0.5 -1 GB) to avoid host machine crash due to lack of memory.
-  JVM Direct Memory > JVM Heap
This is because the Segment Store read cache, Netty and the …
> [pravega] Issue 48: Modify the default values mentioned in the sizing manifests

- charts/pravega-operator/templates/pravega.pravega.io_pravegaclusters_crd.yaml
- charts/pravega/README.md
- charts/pravega/templates/pravega.yaml
- charts/pravega/values.yaml
Add support for configuring readiness and liveness probes for controller and segmentstore
Fixes #74
Made changes in CRD to add the new spec field. And made changes in Pravega charts to configure probes.
Verified that able to configure probes during install
> [pravega-operator/pravega] Issue 74: Adding support for configuring probes

- charts/bookkeeper/Chart.yaml
- charts/bookkeeper/README.md
- charts/bookkeeper/values.yaml
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>
Updating bookkeeper charts to use bookkeeper image 0.10.1
Fixes #79 
Updates the AppVersion and the image version to 0.10.1 inside the bookkeeper charts.
Running the following commands should install the bookkeeper cluster with image 0.10.1
```
helm install bookkeeper pravega/bookkeeper --version=0.10.2
```
> [bookkeeper] Issue 79: Updating AppVersion to 0.10.1

- charts/bookkeeper/Chart.yaml
- charts/pravega/Chart.yaml
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>
Bumps up the chart version of pravega and bookkeeper to 0.10.3
Fixes #73 
Fixes #81 
Bumps up the chart version of pravega and bookkeeper to 0.10.3
N.A.
> [pravega,bookkeeper] Issue 73,81: Bumping chart version to 0.10.3

- charts/bookkeeper-operator/templates/pre-delete-hooks.yaml
Fixed pre-delete hook of bookkeeper operator
Fixes #83
Made changes to look for bk cluster resources only in the watch namespace of operator, if that is provided
Verified the below scenarios
a. Installed a  bkcluster in different namespace operator is not watching
Able to uninstall operator
b. Installed bk cluster in namespace operator is watching
Hook is preventing uninstall of operator
> [bookkeeper-operator] Issue 83: Fixing bookkeeper-operator pre-delete hook

- charts/pravega/README.md
Update the Zookeeper URI and Bookkeeper URI to the correct values in pravega cluster installation guide.
Fixes #78
Updates the Zookeeper URI and Bookkeeper URI to the correct values in pravega cluster installation guide
Install pravega cluster with the updated values of Zookeeper URI and Bookkeeper URI as mentioned in the guide and the cluster should come up.
> [pravega] Issue 78: Update the bookkeeper URI to the right value in pravega cluster installation guide

- charts/pravega-operator/templates/pre-delete-hooks.yaml
Fixed pre-delete hook of pravega operator
Fixes #88
Made changes to look forpravega cluster resources only in the watch namespace of operator, if that is provided
Verified the below scenarios
a. Installed a  pravega cluster in different namespace operator is not watching
Able to uninstall operator
b. Installed pravega cluster in namespace operator is watching
Hook is preventing uninstall of operator
> [pravega-operator] Issue 88: Fixing pravega-operator pre-delete hook

- charts/pravega-operator/templates/pravega.pravega.io_pravegaclusters_crd.yaml
There was an issue upgrade from v1beta1 to v1 in CRD. It was due to conversion webhook is not in the new format
Fixes #39
Updated the conversion webhook to `v1` format
Verified upgrade 
> [pravega-operator] Issue 39: Fixing conversion webhook

- charts/bookkeeper-operator/Chart.yaml
- charts/bookkeeper-operator/README.md
- charts/bookkeeper-operator/values.yaml
Updating appVersion in bookkeeper-operator charts to 0.1.7
Fixes #93
Updates the appVersion from `0.1.6` --> `0.1.7` in bookkeeper-operator charts
Try installing the bookkeeper-operator with the command `helm install [RELEASE_NAME] pravega/bookkeeper-operator --version=[VERSION] --set webhookCert.certName=[CERT_NAME] --set webhookCert.secretName=[SECRET_NAME]` and It should install bookkeeper-operator with 0.1.7 image
> [bookkeeper-operator] Issue 93: Update appVersion to 0.1.7 for bookkeeper-operator

- charts/pravega-operator/Chart.yaml
- charts/pravega-operator/README.md
- charts/pravega-operator/values.yaml
Updating appVersion in pravega-operator charts to 0.5.6 
Fixes #92
Updates the appVersion from `0.5.5` --> `0.5.6` in pravega-operator charts
Try installing the pravega-operator with the command `helm install [RELEASE_NAME] pravega/pravega-operator --version=[VERSION] --set webhookCert.certName=[CERT_NAME] --set webhookCert.secretName=[SECRET_NAME]` and It should install pravega-operator with 0.5.6 image
> [pravega-operator] Issue 92: Update appVersion to 0.5.6 for pravega-operator

- charts/pravega-operator/Chart.yaml
Bumps up the pravega operator chart version to 0.6.3
Fixes #97
Bumps up the pravega operator chart version to 0.6.3
NA
> [pravega-operator] Issue 97: Bumping the chart version to 0.6.3

- charts/bookkeeper-operator/Chart.yaml
Bumps up the bookkeeper operator chart version to 0.2.3
Fixes #96
Bumps up the bookkeeper operator chart version to 0.2.3
NA
> [bookkeeper-operator] Issue 96: Bumping chart version to 0.2.3 

- charts/bookkeeper-operator/README.md
- charts/bookkeeper/README.md
- charts/pravega-operator/README.md
Documenting that the users should deploy the clusters with higher backofflimit if deploying a bookkeeper cluster with a large replica count.
Fixes #90
Updates the documentation to include a note that users should deploy the clusters with higher backofflimit if deploying the bookkeeper cluster with a large replica count
NA
> [bookkeeper] Issue 90: Allowing Bookkeeper for upgrade with large replica count

- charts/pravega/values.yaml
- charts/pravega/values/minikube.yaml
updated `bookkeeper.ledger.size.max` to `256 MB`
Fixes #105
Updated ledger max size to `256 MB`
Verified that able to install cluster with this option
> [pravega] Issue 105: Modifying the default for ledger max size

- charts/pravega/Chart.yaml
- charts/pravega/README.md
- charts/pravega/values.yaml
Change log description
Updating pravega charts to use pravega image 0.10.2
Purpose of the change
Fixes https://github.com/pravega/charts/issues/110
What the code does
Updates the AppVersion and the image version to 0.10.2 inside the pravega charts.
How to verify it
Running the following commands should install the pravega cluster with image 0.10.2
> [pravega] Issue 110: Updating AppVersion to 0.10.2

- charts/pravega/Chart.yaml
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>
Bumps up the chart version of pravega to 0.10.4
Fixes #112 
Bumps up the chart version of pravega to 0.10.4
N.A.
> [pravega] Issue 112: Bumping chart version to 0.10.4

- charts/pravega/Chart.yaml
- charts/pravega/README.md
- charts/pravega/values.yaml
Change log description
Updating pravega charts to use pravega image 0.11.0
Purpose of the change
[Fixes #110](https://github.com/pravega/charts/issues/109)
What the code does
Updates the AppVersion and the image version to 0.11.0 inside the pravega charts.
How to verify it
Running the following commands should install the pravega cluster with image 0.11.0
> [pravega] Issue 109: Updating AppVersion to 0.11.0

- charts/pravega/Chart.yaml
Bumps up the chart version of pravega to 0.10.5
Fixes #121
Bumps up the chart version of pravega to 0.10.5
N.A.
> [pravega] Issue 121: Bumping chart version to 0.10.5

- charts/bookkeeper/Chart.yaml
- charts/bookkeeper/README.md
- charts/bookkeeper/values.yaml
Updating bookkeeper charts to use bookkeeper image 0.10.2
Fixes #122 
Updates the AppVersion and the image version to 0.10.2 inside the bookkeeper charts.
Running the following commands should install the bookkeeper cluster with image 0.10.2
```
helm install bookkeeper pravega/bookkeeper --version=0.10.3
```
> [bookkeeper] Issue 122: Updating AppVersion to 0.10.2

- charts/bookkeeper/Chart.yaml
- charts/bookkeeper/README.md
- charts/bookkeeper/values.yaml
Updating bookkeeper charts to use bookkeeper image 0.11.0
Updating bookkeeper chart version to 0.10.4
Fixes #126, #128
Updates the AppVersion and the image version to 0.11.0 inside the bookkeeper charts.
Running the following commands should install the bookkeeper cluster with image 0.11.0
```
helm install bookkeeper pravega/bookkeeper --version=0.10.4
```
> [bookkeeper] Issue 126: Updating AppVersion to 0.11.0 and bumping up chart version to 0.10.4

- charts/bookkeeper-operator/Chart.yaml
- charts/bookkeeper-operator/README.md
- charts/bookkeeper-operator/values.yaml
Update the bookkeeper operator  app version to `0.1.8`
Fixes #131
Updated bookkeeper operator image version
Try installing the bookkeeper-operator with the command `helm install [RELEASE_NAME] pravega/bookkeeper-operator --version=[VERSION] --set webhookCert.certName=[CERT_NAME] --set webhookCert.secretName=[SECRET_NAME]` and It should install bookkeeper-operator with 0.1.8 image
> [bookkeeper-operator] Issue 131: Updating AppVersion to 0.1.8

- charts/pravega/templates/pravega.yaml
Signed-off-by: Ondřej Kobližek <koblizeko@gmail.com>
Fix indentation for segmentStoreSvcAnnotations in pravega template
Fixes #139 
Fix bad indentation
Generate helm template for pravega with enabled external access and more than one annotations in `segmentStore.service.annotations`
> [pravega] Issue 139: Fix indentation for segmentStoreSvcAnnotations in pravega template

- charts/pravega-operator/templates/pravega.pravega.io_pravegaclusters_crd.yaml
- charts/pravega/templates/pravega.yaml
- charts/pravega/values.yaml
Modified the CRD to add new fields. In Pravega charts provided option to configure it
Fixes #142
Added support for customizing containers, volumes and env variables to segment store pods
Verified install and upgrade with these changes
> [pravega-operator/pravega] Issue 142: Provide support to add customized containers, volumes and env to segment store podss

- charts/pravega/Chart.yaml
- charts/pravega/README.md
- charts/pravega/values.yaml
Updating pravega charts to use pravega image 0.12.0
Fixes #144
Updates the AppVersion and the image version to 0.12.0 inside the pravega charts.
Running the following commands should install the pravega cluster with image 0.12.0
> [pravega] Issue 144: Updating App Version to 0.12.0

- charts/pravega/Chart.yaml
Bumps up the chart version of pravega to 0.10.6
Fixes #146
Bumps up the chart version of pravega to 0.10.6
N/A
> [pravega] Issue 146: Bumping chart version to 0.10.6

- charts/bookkeeper/values.yaml
Increased the readiness timeout in bookkeeper cluster charts
Fixes #148
Increase the readiness probe timeout and period seconds
Verified that Readiness probe check is passing in slow clusters
> [bookkeeper] Issue 148: Increase the readiness timeout in bookkeeper cluster charts

- charts/pravega-operator/Chart.yaml
- charts/pravega-operator/README.md
- charts/pravega-operator/values.yaml
Signed-off-by: anishakj [anisha.kj@dell.com](mailto:anisha.kj@dell.com)
Updating appVersion in pravega-operator charts to 0.5.7 
Fixes #165
Updates the appVersion from `0.5.6` --> `0.5.7` in pravega-operator charts
Try installing the pravega-operator with the command `helm install [RELEASE_NAME] pravega/pravega-operator --version=[VERSION] --set webhookCert.certName=[CERT_NAME] --set webhookCert.secretName=[SECRET_NAME]` and It should install pravega-operator with 0.5.7 image
> [pravega-operator] Issue 165: Update appVersion to 0.5.7 for pravega-operator

- charts/bookkeeper-operator/Chart.yaml
Bumps up the bookkeeper operator chart version to 0.2.5
Fixes #168
Bumps up the bookkeeper operator chart version to 0.2.5
NA
> [bookkeeper-operator] Issue 168: Bumping the chart version to 0.2.5

- charts/pravega/Chart.yaml
Bumps up the chart version of pravega to 0.10.7
Fixes #182 
Bumps up the chart version of pravega to 0.10.7
N/A
> [pravega] Issue 182: Bumping chart version to 0.10.7
